# Generated by Django 5.2.11 on 2026-02-24 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos/galeria/')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='portfolio.projeto')),
            ],
        ),
    ]
