# Generated by Django 5.2.11 on 2026-03-31 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_imagemprojeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='area',
            field=models.CharField(default='A definir', help_text='Ex: 450m²', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='cliente',
            field=models.CharField(default='Confidencial', max_length=100),
        ),
        migrations.AddField(
            model_name='projeto',
            name='localizacao',
            field=models.CharField(default='A definir', help_text='Ex: Lages, SC', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(default='Concluído', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para esconder o projeto do site'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.categoria'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_publicacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem_principal',
            field=models.ImageField(upload_to='projetos/capas/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
