# Generated by Django 5.2.11 on 2026-03-31 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projeto_area_projeto_cliente_projeto_localizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='area',
            field=models.CharField(default='A definir', help_text='Ex: 450m²', max_length=50),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='portfolio.categoria'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_publicacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem_principal',
            field=models.ImageField(upload_to='projetos/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='localizacao',
            field=models.CharField(default='A definir', help_text='Ex: Lages, SC', max_length=200),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
